import React, { useState } from "react";
import "./InvestmentCalculator.scss";

function InvestmentCalculator() {
  const [purchasePrice, setPurchasePrice] = useState(0);
  const [rentalIncome, setRentalIncome] = useState(0);
  const [expenseRatio, setExpenseRatio] = useState(0.35);
  const [interestRate, setInterestRate] = useState(0.04);
  const [loanTerm, setLoanTerm] = useState(30);
  const [downPaymentPercentage, setDownPaymentPercentage] = useState(30);
  const [occupancyRate, setOccupancyRate] = useState(0.95);

  const calculateMetrics = () => {
    const annualRentalIncome = rentalIncome * 12 * occupancyRate;
    const operatingExpenses = annualRentalIncome * expenseRatio;
    const noi = annualRentalIncome - operatingExpenses;
    const capRate = (noi / purchasePrice) * 100;

    const downPayment = purchasePrice * (downPaymentPercentage / 100);
    const loanAmount = purchasePrice - downPayment;
    const monthlyInterestRate = interestRate / 12;
    const numberOfPayments = loanTerm * 12;
    const monthlyMortgagePayment =
      (loanAmount *
        (monthlyInterestRate *
          Math.pow(1 + monthlyInterestRate, numberOfPayments))) /
      (Math.pow(1 + monthlyInterestRate, numberOfPayments) - 1);
    const annualMortgagePayment = monthlyMortgagePayment * 12;

    const annualCashFlow = noi - annualMortgagePayment;
    const roi = (annualCashFlow / downPayment) * 100;

    return {
      capRate,
      annualCashFlow,
      roi,
    };
  };

  const { capRate, annualCashFlow, roi } = calculateMetrics();

  return (
    <div className="investment-calculator">
    <h2 className="investment-calculator__title">Real Estate Investment Calculator</h2>
    <form className="investment-calculator__form">
      <label className="investment-calculator__form-label">
        Purchase Price:
        <input
          type="number"
          className="investment-calculator__form-input"
          value={purchasePrice}
          onChange={e => setPurchasePrice(Number(e.target.value))}
        />
      </label>
      <label className="investment-calculator__form-label">
        Monthly Rental Income:
        <input
          type="number"
          className="investment-calculator__form-input"
          value={rentalIncome}
          onChange={e => setRentalIncome(Number(e.target.value))}
        />
      </label>
      </div>

      <div className="calculator-results">
        <p>Cap Rate: {capRate.toFixed(2)}%</p>
        <p>Annual Cash Flow: ${annualCashFlow.toFixed(2)}</p>
        <p>ROI: {roi.toFixed(2)}%</p>
      </div>
      <div className="calculator-use-case">
        <h3>Use Case</h3>
        <p>
          Use this calculator to estimate the potential return on investment for
          a real estate property. Enter the purchase price, expected rental
          income, and other expenses to calculate the Cap Rate, Annual Cash
          Flow, and ROI.
        </p>
      </div>
      <div className="calculator-terms">
        <h3>Terms and Definitions</h3>
        <ul>
          <li>
            <strong>Cap Rate (Capitalization Rate):</strong> A measure of the
            potential return on a real estate investment, calculated as the Net
            Operating Income divided by the purchase price.
          </li>
          <li>
            <strong>Net Operating Income (NOI):</strong> The total income
            generated by the property minus operating expenses.
          </li>
          <li>
            <strong>ROI (Return on Investment):</strong> A measure of the
            profitability of an investment, calculated as the net profit divided
            by the initial investment cost.
          </li>
          <li>
            <strong>Expense Ratio:</strong> The ratio of operating expenses to
            the gross income of the property, indicating the efficiency of
            property management.
          </li>
          <li>
            <strong>Interest Rate:</strong> The percentage charged on the
            borrowed capital, affecting the monthly mortgage payments.
          </li>
          <li>
            <strong>Loan Term:</strong> The duration over which the loan is
            scheduled to be repaid, typically expressed in years.
          </li>
          <li>
            <strong>Down Payment Percentage:</strong> The portion of the
            property's purchase price paid upfront, expressed as a percentage of
            the total price.
          </li>
          <li>
            <strong>Occupancy Rate:</strong> The ratio of rented or used space
            to the total available space, indicating the property's ability to
            attract and retain tenants.
          </li>
        </ul>
      </div>
    </div>
  );
}

export default InvestmentCalculator;
